### ISSUE TITLE
Deprecation warning CLI_OPTIONS_SCHEMA

### ISSUE THREAD

**Issue by phancox** [serverless-heaven/serverless-webpack#793] opened 2021-04-22 01:31 UTC
# This is a (Bug Report)

## Description
When running serverless deploy:
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessWebpack for "out"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA

Similar or dependent issue(s):

## Additional Data
* serverless-webpack (5.4.1)
* webpack (5.35.0)
* serverless (Framework Core: 2.37.1, Plugin: 4.5.3, SDK: 4.2.2, Components: 3.9.0)
* Operating System: Amazon Linux 2

**Comment by j0k3r** [comment] 2021-04-22 05:05
Duplicate of #764
Will be fixed in 5.4.2

**Closed by j0k3r** 2021-04-22 05:05 UTC
