### ISSUE TITLE
Unable to import local files

### ISSUE THREAD

**Issue by EdByrnee** [serverless-heaven/serverless-webpack#214] opened 2017-09-03 14:40 UTC
# This is a Bug Report
## Description

When I import my local files I have to specify the file extension otherwise webpack throws an error

`import { Student } from "./student.ts";`
Works fine 👍 

`import { Student } from "./student";`
Throws error:
`ERROR in ./handler.ts
Module not found: Error: Can't resolve './student' in '/Users/edwardbyrne/Desktop/my-service'
 @ ./handler.ts 3:16-36
`

 Very strange!

## Additional Data
```

webpack.config.js
const path = require('path');
// eslint-disable-next-line import/no-unresolved
const slsw = require('serverless-webpack');

module.exports = {
  entry: slsw.lib.entries,
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  module: {
    loaders: [
      { test: /\.ts(x?)$/, loader: 'ts-loader' },
    ],
  },
};

```

**Comment by HyperBrain** [comment] 2017-09-03 14:48
It seems that it has something to do with your loader configuration. Since version 2 webpack changed the loader configuration to be like this:
```
module: {
	rules: [
		{
			test: /\.(ts|tsx)$/,
			use: [
				{
					loader: "ts-loader"
				}
			],
		}
	]
}
```

Can you adapt your configuration to match the new semantics for webpack 2+?

**Comment by HyperBrain** [comment] 2017-09-03 16:58
Hi @kikar and @jussikinnula 
Would you mind to help out here? My experience with TypeScript is quite limited, but I know that you use TS in your projects 😄 . Thank you.

**Comment by jussikinnula** [comment] 2017-09-08 06:24
@EdByrnee, here you go :-)

I have a starter repository for webpack + Serverless + TypeScript:
https://github.com/jussikinnula/serverless-typescript-starter

By default webpack only searches for files ending with `.js`, but you can easily add also `.ts` - so that you can import also them without using the file extension:
https://github.com/jussikinnula/serverless-typescript-starter/blob/master/webpack.config.js#L16-L19

On the starter I'm prioritising `.ts` over `.js`, which means that if there's filenames with both extensions available - `.ts` will be used.

**Comment by HyperBrain** [comment] 2017-09-14 23:44
@jussikinnula Thanks for providing the information 🥇 
@EdByrnee Any news on the topic? Did you manage to solve the problem?

**Comment by EFCniux** [comment] 2017-09-18 15:56
Hello @HyperBrain, I can confirm the suggested fix works.

For reference, I was using the default serverless typescript template (sls create --t aws-nodejs-typescript), with the latest versions of the default plugins:
```
"devDependencies": {
    "webpack": "^3.6.0",    
    "serverless-webpack": "^3.0.0",
    "typescript": "^2.5.2",    
    "ts-loader": "^2.3.7"
},
```

The template is probably outdated and should be changed.

This is the current webpack.config.js:
```
const path = require('path');
const slsw = require('serverless-webpack');

module.exports = {
  target: 'node',  
  entry: slsw.lib.entries,
  resolve: {
    extensions: ['.ts', '.js', '.tsx', '.jsx', '.json'],
    modules: [ 'node_modules' ]
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  module: {
    loaders: [
      { test: /\.ts(x?)$/, loader: 'ts-loader' },
    ],
  },
  
};
```

**Comment by franciscocpg** [comment] 2017-09-18 17:53
@HyperBrain 
https://github.com/serverless-heaven/serverless-webpack/pull/227
No need to add `modules: [ 'node_modules' ]` because the [resolve-modules](https://webpack.js.org/configuration/resolve/#resolve-modules) already defaults to `node_modules`.

**Comment by HyperBrain** [comment] 2017-09-18 18:06
@franciscocpg Nice. Thank you 👍 .

I will merge the PR later or tomorrow. We should also adapt the SLS template, right?

**Comment by franciscocpg** [comment] 2017-09-18 18:09
Yes, just after you merged it I'm going to update the template.

**Comment by HyperBrain** [comment] 2017-09-18 18:21
Merged 😄

**Closed** 2017-09-18 18:21 UTC
Labels: help wanted

**Comment by franciscocpg** [comment] 2017-09-18 21:58
@HyperBrain 
https://github.com/serverless/serverless/pull/4281
