### ISSUE TITLE
Webpack does not run before tests with serverless-jest-plugin

### ISSUE THREAD

**Issue by lpgeiger** [serverless-heaven/serverless-webpack#143] opened 2017-07-04 00:35 UTC
# This is a Documentation issue

## Description
(I'm assuming this is a documentation issue, but it may be a feature if this case has not been contemplated.)

I'm trying to ensure that webpack runs before the testing plugin. Currently I'm using the https://github.com/SC5/serverless-jest-plugin

It appears tests are running the uncompiled code. This means I'm not catching all the syntax errors lambda runtime does not support.

## Reproduction
It's a bit tricky to reproduce this error, since you'd have to compare the jest test run results to that of a deployed function. 
You can break the webpack integration by breaking the config file : 
```
module.exports = {
  entry: null,
...
````
The test runner will not catch this error, which implies that webpack is not running before the tests.
The only way to catch this is by running `serverless webpack serve`

## Additional Data

package.json
```
    "babel-core": "^6.13.2",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-runtime": "^6.12.0",
    "babel-polyfill": "6.13.0",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-stage-0": "^6.5.0",
    "serverless-jest-plugin": "^0.1.5",
    "serverless-webpack": "^1.0.0-rc.3",
    "webpack": "^1.13.1"
```
serverles.yml
```
plugins:
  - serverless-jest-plugin
  - serverless-webpack
```

**Comment by HyperBrain** [comment] 2017-07-04 08:49
Can you post the `plugins` section from you `serverless.yml`? The order there defines the execution order of the plugins. It would be great to know, if the test plugin is set before or after the webpack plugin.

**Comment by lpgeiger** [comment] 2017-07-04 18:23
Thanks @HyperBrain this is the order of plugins. It's a bit tricky to reproduce this error, since you'd have to compare the jest test run results to that of a deployed function.
```
plugins:
  - serverless-jest-plugin
  - serverless-webpack
```

**Comment by lpgeiger** [comment] 2017-07-04 18:28
It's a bit tricky to reproduce this error, since you'd have to compare the jest test run results to that of a deployed function. 
You can break the webpack integration by breaking the config file : 
```
module.exports = {
  entry: null,
...
````
You can only catch this by running `serverless webpack serve`
The test runner will not catch this error, which implies that webpack is not running before the tests.

**Comment by HyperBrain** [comment] 2017-07-04 18:56
Did you try to reverse the order of the plugins already, so that webpack comes before jest? The reason I ask, is that Serverless executes the plugin integrations exactly in the order how they are specified in the serverless.yml.
If you add webpack AFTER jest, it could be that jest operates on uncompiled sources.

If a reverse order does not help, I will try to check the sources of the jest plugin and see how exactly it integrates with serverless.

**Comment by lpgeiger** [comment] 2017-07-05 04:56
@HyperBrain Yes I've tried both orders, the results are the same. Webpack seems to not be running before the test suite. Thanks in advance.

**Comment by HyperBrain** [comment] 2017-07-05 08:58
Then this is definitively a bug (although I'm not sure where - in the jest plugin or here) that has to be fixed after a deeper analysis. I'll compare the hooks that are used by both plugins and check if the hooks can be adjusted in one of the plugins to make it work with a well-defined execution order.
If anyone else could dive into that too, would be very appreciated 😃

**Comment by HyperBrain** [comment] 2017-07-05 09:18
Just thought about easier reproduction steps. It should be reproducible, if you use e.g. Node 4 and include some ES6 code, that is not understood natively by the use Node version.
If it runs on uncompiled code then, it should bail out.

Maybe using the "import and export" syntax or destructuring should do the trick (see https://kangax.github.io/compat-table/es6/)

**Comment by hassankhan** [comment] 2017-07-05 18:05
Just had a look at `serverless-jest-plugin`'s hooks from [here](https://github.com/SC5/serverless-jest-plugin/blob/master/index.js), and it doesn't look like it binds to any event that `serverless-webpack` uses.

Do you run your tests through the plugin or directly with Jest, @lpgeiger?

**Comment by HyperBrain** [comment] 2017-07-05 18:24
@hassankhan Yes, you're right. The jest plugin commands do not trigger `package:compileFunctions` (see https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406) at all, so invoking the plugin through one of its commands won't trigger any build.

A possible solution would be to change the jest plugin's lifecycle as follows [here](https://github.com/SC5/serverless-jest-plugin/blob/master/index.js#L93-L96):

```
'create:function:create': () =>
  BbPromise.bind(this)
   .then(() => this.serverless.pluginManager.spawn('package'))    // INSERT THIS
   .then(() => createFunction(this.serverless, this.options))
   .then(() => createTest(this.serverless, this.options)),
```

Then the test function created [here](https://github.com/SC5/serverless-jest-plugin/blob/master/lib/create-function.js) could be built from the function compiled with Webpack
which is located in `.serverless` at that point of time.

I'm not sure if the whole package lifecycle has to be started or the compileFunctions would be sufficient. For an initial test I would go with the package.

So this is not anything that can be solved here, but has to be solved in the jest plugin.
Maybe I can spare some time to fix it...

**Comment by hassankhan** [comment] 2017-07-05 18:37
At @EndemolShineGroup, we only have integration tests for our handler functions. We keep the handlers as thin as possible, and shift logic to a `src/` folder, which *is* unit-tested.

To run the tests, we invoke Jest directly. For integration tests, we deploy before (since we need an environment to actually test in). We find that running any sort of integration tests locally tends to mostly be a waste of time because of all the various differences between a Lambda environment and a local developer environment.

**Comment by lpgeiger** [comment] 2017-07-05 22:19
@HyperBrain thanks for identifying this. Are there ANY serverless test suites that would work out of the box?

@hassankhan thanks for the input. 

> We find that running any sort of integration tests locally tends to mostly be a waste of time 

Yes that's what I'm finding. It seems strange that none of the local emulation solutions package the correct target runtime. 
I don't think I'd be comfortable doing integration tests only as you describe. That would be fine for simple resources, but more complex apps would need unit tests.

**Comment by HyperBrain** [comment] 2017-07-05 23:00
@lpgeiger Maybe [mocha-webpack](https://www.npmjs.com/package/mocha-webpack) would work for the unit tests - you can specify a webpack config.

**Comment by HyperBrain** [comment] 2017-07-07 11:04
I'll remove the bug tag, as it is obviously no bug for this project. I'll close it as soon as the discussion in here has been finalized - feel free to continue discussing even after that 😄

**Comment by lpgeiger** [comment] 2017-07-07 15:16
@HyperBrain Thanks for looking into it. I'm not familiar with the serverless plugin system. Can you give me a hint about how one might implement a  hook into 'serverless-webpack' the test runner I'm using: 'serverless-jest-plugin' ? Thanks in advance,

**Comment by lpgeiger** [comment] 2017-07-11 17:51
@HyperBrain  I See that the issues is fixed in serverless-webpack, it seems to work in my tests. Can you confirm that your implementation is working too? Thanks in advance!

**Comment by HyperBrain** [comment] 2017-07-11 18:20
@lpgeiger Just saw that there were fixes done in the SC5 plugins (mocha plugin). I'm not sure if I can double check it in the next days. Good, if it works for you. Maybe someone else can try it too.
We can leave this task open for some time until we're really sure that it works now.

**Comment by HyperBrain** [comment] 2018-01-22 11:13
I'll close this one for now. There was no additional feedback for a long time.
Feel free to continue discussion here, if there's anything left to mention.

**Closed by HyperBrain** 2018-01-22 11:13 UTC
Labels: help wanted
