### ISSUE TITLE
serverless webpack slsw.lib.entries empty

### ISSUE THREAD

**Issue by alsenydiallo** [serverless-heaven/serverless-webpack#1038] opened 2022-01-13 21:18 UTC
# This is a (Bug Report / Feature Proposal)

## Description

For bug reports:
* What went wrong?
Running serverless webpack to build my projects is working without any error; however it is not including any of the project code

* What did you expect should have happened?
I expect the webpack to package all code, this worked previously while on `serverless@1.67.0` , `"serverless-webpack": "^5.3.5",` and `"webpack": "^5.64.4",` 

Needed to update serverless due to `Receiving TypeError: Cannot read property 'stepFunctions' of undefined since 3.0.0 release` [Issue Link](https://github.com/serverless-operations/serverless-step-functions/issues/454)

As a result I updated the following packages 
```
npm install --save-dev serverless@2.71.0
npm install --save-dev webpack@5.65.0
npm install --save-dev serverless-webpack@5.6.0
npm install --save-dev dotenv-webpack@7.0.3
```

```
Serverless: Copying existing artifacts...
Serverless: Setting artifact for function 'createAccount' to '.serverless/app-backend-api.zip'
Serverless: Setting artifact for function 'updateAccount' to '.serverless/app-backend-api.zip'
Serverless: Setting artifact for function 'getAccountById' to '.serverless/app-backend-api.zip'
....
Serverless: Setting artifact for function 'getAccountActivityById' to '.serverless/app-backend-api.zip'
Serverless: Setting artifact for function 'getAccountStatements' to '.serverless/app-backend-api.zip'
Serverless: Setting artifact for function 'getAccountStatementsById' to '.serverless/app-backend-api.zip'
```

* What was the config you used?
```
const path = require('path');
const slsw = require('serverless-webpack');
const WebpackPermissionsPlugin = require('./webpack-permissions.plugin');
const nodeExternals = require('webpack-node-externals');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const Dotenv = require('dotenv-webpack');

const entries = {};
Object.keys(slsw.lib.entries).forEach((key) => (entries[key] = ['./source-map-install.js', slsw.lib.entries[key]]));
console.log(entries);
console.log(slsw.lib.entries);
const destPath = path.join(__dirname, '.webpack');
module.exports = {
  entry: entries,
  output: {
    libraryTarget: 'commonjs',
    path: destPath,
    filename: '[name].js',
  },
  target: 'node',
  node: {
    __dirname: false,
    __filename: false,
  },
  mode: slsw.lib.options.stage === 'local' ? 'development' : 'production',
  // Generate sourcemaps for proper error messages
  devtool: 'source-map',
  // we use webpack-node-externals to excludes all node deps.
  // You can manually set the externals too.
  externals: [nodeExternals({ modulesDir: path.resolve(__dirname, './node_modules') })],
  module: {
    rules: [
      {
        test: /\.ts(x?)$/,
        loader: 'ts-loader',
        exclude: [/\.(test|e2e)\.ts$/],
      },
    ],
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js'],
    plugins: [new TsconfigPathsPlugin.TsconfigPathsPlugin({ configFile: path.resolve(__dirname, './tsconfig.json') })],
  },
  optimization: {
    minimize: false,
  },
  plugins: [
    new Dotenv(),
    new CopyWebpackPlugin({
      patterns: [{ from: 'bin', to: 'bin' }],
    }),
    new WebpackPermissionsPlugin(),
  ],
};
```

source-map-install.js content 

`require('source-map-support').install();`
`"source-map-support": "^0.5.21"`

* What stacktrace or error message from your provider did you see?
```
> serverless webpack

{}
{}
Serverless: Bundling with Webpack...
Failed to load ./.env.
asset bin/mediainfo-curl 0 bytes [emitted] [from: bin/mediainfo-curl] [copied]
webpack compiled successfully in 48 ms
Serverless: No external modules needed
Serverless: Copying existing artifacts...

```

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):
* #12345

## Additional Data

* ***Serverless-Webpack Version you're using***: "^5.6.0"
* ***Webpack version you're using***: "^5.65.0"
* ***Serverless Framework Version you're using***: "^2.71.0"
* ***Operating System***: Mac OS Big Sur Version 11.4
* ***Stack Trace (if available)***:

**Comment by alsenydiallo** [comment] 2022-01-13 21:23
Project Structure 

```
╰─$ tree -L 1
.
├── README.md
├── api
│   ├── account
│ ...
│   ├── user_signup
│   └── waitlist
├── bin
│   └── mediainfo-curl
├── docker-compose.yml
├── env.yml
├── errors
│   ├── http
│   ├── index.ts
│   └── runtime
├── helper
│   ├── currencies.ts
│   ├── environment.ts
│   ├── error-handler.ts
│   ├── helper.ts
│   └── logger.ts
├── interfaces
│   ├── account.interface.ts
│ ...
│   └── user-data.interface.ts
├── jest.config.js
├── kms_key.yml
├── models
│   ├── DynamoDB
│   └── QLDB

├── node_modules
├── package-lock.json
├── package-lock.json
├── package.json
├── serverless
│   ├── functions
│   └── resources
├── serverless.yml
├── services
│   ├── account.service.ts
│ ...
│   └── user-data.service.ts
├── sonar-project-build.properties
├── sonar-project.js
├── sonar-project.properties
├── source-map-install.js
├── test-report.xml
├── tests
│   └── api_tests
├── tsconfig.json
├── webpack-permissions.plugin.js
└── webpack.config.js

```

**Comment by alsenydiallo** [comment] 2022-01-14 21:10
the plugin "serverless-dir-config-plugin": "^0.1.5"is broken since I updated to "serverless": "^2.71.0".
This is mentioned on the **serverless-dir-config-plugin** [website](https://www.serverless.com/plugins/serverless-dir-config-plugin) that this could happen.

Quote from **serverless-dir-config-plugin**

> Warnings
> Serverless.js doesn't provide hooks to append to the config file. This plugin ends up making some assumptions to work.
> 
> Currently the framework loads all the plugins before it does anything. This allows the plugin to look for the files and append them to the configuration before anything happens.
> 
> After the configuration is loaded all the variables get resolved. The plugin monkeypatches this process so it can add in function names once the variables are all set.
> 
> This means that right now the way the plugin works is very fragile. If the Serverless.js changes the way they load things - this plugin will break. I am hoping that after confirming that this plugin is useful I will submit a PR that looks at giving plugins access to the hooks that I'm basically inventing

* Any plan for serverless to provide a way to separate your functions declaration and resource from the main serverless.yml file ? a feature similar to what **serverless-dir-config-plugin** provided - [See Here](https://www.serverless.com/plugins/serverless-dir-config-plugin)

**Comment by vicary** [comment] 2022-01-16 10:11
`serverless-webpack` is a plugin for `serverless`, not the core repo. You may start a discussion at https://github.com/serverless/serverless if you want to know the general direction.

If you're sure the problem is caused by `serverless-dir-config-plugin`, you may reference a javascript file via the built-in `serverless.yml` `${file(...js)}` syntax and parse your directory files there. In fact that's the method I used all along. I don't think `serverless` supports dynamic configuration changes via lifecycle hooks, so plugins are no longer viable since V2.

If you're not sure, please share your `serverless.yml` so we can reproduce the issue.

**Comment by alsenydiallo** [comment] 2022-01-17 19:32
Considering all the research that I have done, my conclusion is that the solution currently available is to
- Declare all your resources on the serverless.yml file 
- or reference then on the serverless.yml with the format `${file(...js)}`

I think the Serverless Team should look into adding this feature `splitting your functions and resource declaration into different folder or .yml file`

**Comment by vicary** [comment] 2022-01-18 05:32
Closing this issue since it will be off-topic for this repo from now on.

---

Speaking from my own experience, I love the flexibility and the room for users' opinions.

We have lots of AppSync and API Gateway projects in production, our AppSync projects use `serverless-appsync-plugin` which somehow favors a different directory structure than those with apigw.

I would rather have control over the directory structure, since that alone evolved a few times over the last few years to fit the growth of my dev team.

This `.js` file served as a fine tool for team leads to enforce/assist project structures within the team, and it also reduces the learning curve for both the Serverless Framework and AppSync.

**Closed by vicary** 2022-01-18 05:32 UTC
