### ISSUE TITLE
Serverless: WARNING: Could not determine version of module xxxxx

### ISSUE THREAD

**Issue by axelblomberg** [serverless-heaven/serverless-webpack#805] opened 2021-04-28 15:54 UTC
# This is a Bug Report

## Description

Error example in detail
`Serverless: Invoke webpack:package`
`Serverless: WARNING: Could not determine version of module arrify`

Hi. We have an issue where our root hoisted dependencies (using Lerna) cannot be resolved correctly when we bundle and webpack:package runs. This is causing the bundled package.json file to include referenced version as an empty string, see below.

`"dependencies": {`
`"arrify": "",`
`}`

The general issue with this is that dependencies are automatically resolved to latest version which can cause issues if there are breaking changes and so on.

I noticed that there were a version published 8 hours ago by @j0k3r where this functionality was included;

![image](https://user-images.githubusercontent.com/17126470/116434262-8eb1df00-a84a-11eb-9732-ab1bbeb669ef.png)

However, this did not seem to do the trick. Anyone with similar issues using monorepo, serverless and serverless-webpack?

Similar or dependent issue(s):
* #689

## Additional Data

* ***Serverless-Webpack Version you're using***: 5.4.2
* ***Webpack version you're using***: 4.16.2
* ***Serverless Framework Version you're using***: 1.83.2

**Comment by j0k3r** [comment] 2021-04-28 18:05
Could you share your serverless configuration and packages.json?

**Comment by axelblomberg** [comment] 2021-04-28 19:06
I'll enclose the important stuff. Everything that is not explicitly versioned inside subpackages package.json gets the empty string.

Strucutre is;

> root
> /node_modules (everything hoisted)
> /package.json (root deps, lerna for example)
> /serverless.webpack.config.js
> /folder1/package1/package.json (package specific, gets hoisted to root)
> /folder1/package1/serverless.yml
> /folder1/package1/src
> /folder1/package2/package.json
> /folder1/package2/serverless.yml
> /folder1/package2/src

Serverless config

```
 webpack:
    webpackConfig: ../../serverless.webpack.config.js
    includeModules:
       nodeModulesRelativeDir: ../../

```
serverless.webpack.config.js

```
// webpack.config.js
const slsw = require("serverless-webpack");

module.exports = {
  entry: slsw.lib.entries,
  target: "node",
  // Generate sourcemaps for proper error messages
  devtool: 'source-map',
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [
    /^[@a-z\-0-9]+$/
  ],
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  optimization: {
    // We do not want to minimize our code.
    minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  resolve: {
    extensions: [
      '.js',
      '.json',
      '.ts',
      '.tsx'
    ]
  },
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: [{
            loader: 'ts-loader',
            options: {
              transpileOnly: true
            }
          }],
        }
      ]
  }
};
```

**Comment by j0k3r** [comment] 2021-04-28 19:52
I see you are using version 5.4.2, but what I merged isn't available in that release. It's on master actually and not yet part of a release. It'll be part of the upcoming 5.5.0.

**Comment by axelblomberg** [comment] 2021-04-29 07:46
Ah ok! Missed that it wasn't included in that release. Reading the READme kinda gives the impression that it's a feature that's available for the latest version.

Do you have any other ideas? When do you expect to release 5.5.0?

**Comment by j0k3r** [comment] 2021-04-29 07:50
In the coming days I think.
You can follow the milestone: https://github.com/serverless-heaven/serverless-webpack/milestone/35

**Comment by axelblomberg** [comment] 2021-05-06 09:19
@j0k3r Any updates on the planned release day?

**Comment by j0k3r** [comment] 2021-05-06 09:23
As soon as all PRs got merged.
I hope as soon as possible.

**Comment by j0k3r** [comment] 2021-05-10 19:39
I've just released 5.5.0, can you give it a try?

**Comment by chaoyangnz** [comment] 2021-06-11 07:03
still have the issue

**Comment by ypxing** [comment] 2021-08-30 09:02
Hi @axelblomberg I cannot reproduce your issue. Can you share your ```package.json (package specific, gets hoisted to root)```

Also the issue you reported is different from what #689 resolves.
The fix resolves issue ```WARNING: Could not check for peer dependencies```

Your issue is ```WARNING: Could not determine version of module arrify```

**Comment by ypxing** [comment] 2021-08-30 09:03
Hi @chaoyangnz 

Would you please share more information? Thanks

**Closed** 2022-03-29 07:37 UTC
