### ISSUE TITLE
invoke local compiles in-memory

### ISSUE THREAD

**Issue by gdi2290** [serverless-heaven/serverless-webpack#298] opened 2017-12-10 04:43 UTC
For feature proposals:
invoking lambda locally will overwrite built bundle. For one-off local invokes the serverless-offline  will run into errors since the built bundle isn't there anymore

**Comment by HyperBrain** [comment] 2017-12-10 10:47
Hi @gdi2290 ,

this is a duplicate of #288 , which addresses exactly the same problem: while running serverless offline, it is not possible to run a single local invoke as it removes the compiled output and makes offline crash.

**Closed by HyperBrain** 2017-12-10 10:47 UTC
Labels: duplicate
