### ISSUE TITLE
Can't require a git dependency with npm 5.6.0, deployment doesn't package this correctly

### ISSUE THREAD

**Issue by DanSchick** [serverless-heaven/serverless-webpack#310] opened 2018-01-18 21:40 UTC
# This is a (Bug Reportl)

## Description
Related to the closed issue https://github.com/serverless-heaven/serverless-webpack/issues/295

For bug reports:
* What went wrong?
When I had a git dependency in package.json, trying to require() that dependency in a function handler resulted in  a cannot find module error. Without serverless-webpack, requiring this dependency with serverless alone worked.

**Steps to reproduce**:
- With npm 5.6.0, create a new aws-nodejs serverless project
- put some github dependency in package.json (ex: 'expressjs/express') and npm install
- require() this module in the handler.js function
- serverless deploy and serverless invoke function, should go through fine
- then get serverless webpack set up (webpack.config.json, serverless-webpack in serverless.yml plugins, etc)
- serverless deploy and serverless invoke function
- this results in a module cannot be found error for me.

* What did you expect should have happened?
That the dependency would be bundled by webpack so I could import it
* What was the config you used?
Bash on Ubuntu on Windows
node 8
npm 5.6.0
serverless 1.25
* What stacktrace or error message from your provider did you see?
"Cannot find module error"

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.
* If there is additional config how would it look

Similar or dependent issue(s):
* #295

## Additional Data

This was connect to https://github.com/npm/npm/issues/19356 this NPM issue in #295, but that was closed.

* ***Serverless-Webpack Version you're using***:
4.1.0
* ***Webpack version you're using***:
* ***Serverless Framework Version you're using***:
1.25
* ***Operating System***:
bash on ubuntu on windows
* ***Stack Trace (if available)***:

**Comment by HyperBrain** [comment] 2018-01-18 22:00
Hi @DanSchick . Thanks for the report.

The only know workaround currently would be to downgrade npm to a version prior to 5.5 as long as it is not yet fixed in npm or use service level packaging. I'd personally advise to do the downgrade, because service level packaging will eliminate all advantages that you get with individual packaging.

**Comment by HyperBrain** [comment] 2018-02-26 10:16
@DanSchick I investigated the changelogs for npm 5.7.1 and saw that the git fix as well as some prune fixes were in there. I also saw, that they did not comment the old open tasks and inform users that this might be closed.
So I'd propose that we do some tests with `npm@5.7.1` to see if the problem is fixed. If it is, we can add a section for supported npm versions to the docs (`<5.5 && >=5.7.1`)

**Comment by HyperBrain** [comment] 2018-02-28 20:20
@serverless-heaven/serverless-webpack-contributors Anyone of you already checked if npm 5.7.1 fixed the unexpected "uninstall" of git references in the dependencies?

**Comment by franciscocpg** [comment] 2018-02-28 20:30
Hi @HyperBrain.
To be honest I'm just using `yarn` lately so I can help much here.

**Comment by HyperBrain** [comment] 2018-02-28 20:31
@franciscocpg No problem - then you're my candidate to test the yarn integration as soon as I've finished it 😄

**Comment by franciscocpg** [comment] 2018-02-28 20:32
With pleasure :relaxed:

**Comment by HyperBrain** [comment] 2018-03-13 15:00
There is now a npm version hint in the README that tells users to use npm `< 5.5 | >= 5.7.1` which circumvents the problem of broken npm versions.

Closing this now as it is still available as reference within the closed issues.

**Closed by HyperBrain** 2018-03-13 15:01 UTC
Labels: bug
