### ISSUE TITLE
Useless warning on excluded modules WARNING: Could not determine version of module ###

### ISSUE THREAD

**Issue by jer-sen** [serverless-heaven/serverless-webpack#991] opened 2021-11-06 10:59 UTC
# This is a Bug Report

## Description

For bug reports:
* What went wrong?
Warnings during builds `WARNING: Could not determine version of module ###`
* What did you expect should have happened?
No warning. Since the modules are excluded their version should not be determined.
* What was the config you used?
The module is not in dependecies, but in webpack `externals` and `forceExclude`
* What stacktrace or error message from your provider did you see?
`WARNING: Could not determine version of module ###`

Similar or dependent issue(s): non found

## Additional Data

* ***Serverless-Webpack Version you're using***: `serverless-webpack@5.5.5`
* ***Webpack version you're using***: `webpack@5.61.0`
* ***Serverless Framework Version you're using***: `Framework Core: 2.64.1`
* ***Operating System***: `Windows 10`
* ***Stack Trace (if available)***: NA

**Comment by j0k3r** [comment] 2021-11-07 19:28
I'm sorry but without example, config or technical stuff we can't help you.

**Comment by jer-sen** [comment] 2021-11-07 23:06
@j0k3r what do you need exactly?

The log comes from this line: https://github.com/serverless-heaven/serverless-webpack/blob/9b5c29030549698d2548ee2b020c8e81a9f22e51/lib/packExternalModules.js#L149
It seems that `serverless-webpack` looks for a version of any external module (and is not happy if module is not in `depedencies` nor in `devDependencies`) even if it is _force exluded_. Is it really what we want?

`mongodb` module requires some optional modules found by webpack so I've added these to externals since I don't want to use theim. But I get the warning during build...

**Comment by vicary** [comment] 2021-11-08 07:01
@jer-sen I would say your recent explanation and context makes things much more easier than starting a conversation with the word "useless", because an incomplete understanding of an issue by the team may lead to an incomplete solution that ends up breaking other things.

If you're kind enough to make a minimal reproducible repo, and it turns out to be a legit bug, it will help us adapt that into a regression test.

**Comment by jer-sen** [comment] 2021-12-02 08:41
@vicary here is a small repro, just run `yarn` and `serverless deploy`, you will see these logs with warnings on excluded modules:

```
$ serverless deploy
Serverless: Bundling with Webpack...
asset test.js 628 KiB [emitted] [minimized] (name: test) 1 related asset
runtime modules 670 bytes 3 modules
orphan modules 42 bytes [orphan] 1 module
modules by path ./node_modules/mongodb/ 754 KiB 98 modules
modules by path ./node_modules/whatwg-url/ 82.4 KiB
  modules by path ./node_modules/whatwg-url/lib/*.js 81 KiB 11 modules
  modules by path ./node_modules/whatwg-url/*.js 1.4 KiB
    ./node_modules/whatwg-url/index.js 1.23 KiB [built] [code generated]
    ./node_modules/whatwg-url/webidl2js-wrapper.js 170 bytes [built] [code generated]
optional modules 294 bytes [optional] 7 modules
modules by path ./node_modules/tr46/ 197 KiB
  modules by path ./node_modules/tr46/lib/*.js 64.9 KiB 2 modules
  ./node_modules/tr46/index.js 7.18 KiB [built] [code generated]
  ./node_modules/tr46/lib/mappingTable.json 125 KiB [built] [code generated]
18 modules
webpack compiled successfully in 5318 ms
Serverless: WARNING: Could not determine version of module bson-ext
Serverless: WARNING: Could not determine version of module kerberos
Serverless: WARNING: Could not determine version of module snappy
Serverless: WARNING: Could not determine version of module snappy
Serverless: WARNING: Could not determine version of module aws4
Serverless: WARNING: Could not determine version of module mongodb-client-encryption
Serverless: Excluding external modules: bson-ext, kerberos, snappy, saslprep@1.0.3, aws4, mongodb-client-encryption
Serverless: No external modules needed
Serverless: Copying existing artifacts...
Serverless: Packaging service...
```

[serverless-webpack.zip](https://github.com/serverless-heaven/serverless-webpack/files/7640345/serverless-webpack.zip)

**Comment by kwajiehao** [comment] 2021-12-14 21:04
I'm facing a similar error - despite using `forceExclude` as specified in the docs, I'm still getting `WARNING: Could not determine version of module aws-sdk`

**Comment by jer-sen** [comment] 2022-01-03 16:41
@vicary did you have time to have a look on my repro?

**Comment by vicary** [comment] 2022-01-04 18:09
@jer-sen My apologies, my team is catching up on a quarterly milestone and I am in the middle of some insane schedules. I'll try to squeeze out some time in a week or two.

**Comment by jer-sen** [comment] 2022-09-24 21:55
@vicary any update?

**Comment by vicary** [comment] 2022-09-25 08:46
@jer-sen The behavior can be reproduced and it is an expected behavior.

Marking a module as external means you want it to be included in the final bundle, `forceExclude` comes the step afterwards. To remove the warning, simply install the externals as `devDependencies`. They won't be included as long as you have `forceExclude` in place.

**Comment by vicary** [comment] 2022-09-25 08:59
@jer-sen I also found another approach. Your provided project archive can be bundled without marking the externals, i.e.

1. I deleted the whole `includeModules` section from `serverless.yml`, and
2. They stay uninstalled as it was.

It bundles without problem, let me know if this works in your case.

**Comment by jer-sen** [comment] 2022-09-25 20:17
@vicary what about a module you don't want to include in a build but which is in your node_modules as an indirect dependency. If you don't add it to webpack externals, it will be found and bundled by webpack. But if you add it to externals and it's an indirect dependency, I think there will be the warning `Could not determine version of module ###`.

Also if it's not installed and if you don't put it in externals, if one day it arrives in your node_modules (for an other build of a monorepo or as an indirect or dev dependency) it will be bundled by webpack without being noticed.

I think the safest way is to add any optional dependency you don't want in externals and forceExclude.

**Comment by vicary** [comment] 2022-09-26 07:40
@jer-sen No worries.

As long as you are using the *packager* option, your `node_modules` is not directly used. `serverless-webpack` will  perform clean install inside `.webpack` directory, and then put that into the final archive in the `.serverless` directory.

It is simply not designed to exclude something never existed, it still works, we only give a warning to let you know it doesn't make sense.

If you don't like the warning, install the optional dependencies and it will be excluded as per your `forceExclude` option.

Closing as a non-issue for the moment.

If you think something should be fixed, feel free to add more context with further comments.

**Closed by vicary** 2022-09-26 07:40 UTC

**Comment by jer-sen** [comment] 2022-09-26 09:33
@vicary I think I was looking for what the IgnorePlugin is built for. Forget what I have written before and thanks for your great work.

**Comment by vicary** [comment] 2022-09-26 10:57
Glad you solved the issue! We may add that into docs if more users found this to be a problem in the future.
