### ISSUE TITLE
Empty files in serverless package zip

### ISSUE THREAD

**Issue by janoist1** [serverless-heaven/serverless-webpack#682] opened 2021-01-23 13:53 UTC
# This is a (Bug Report / Feature Proposal)
**Bug**

## Description

For bug reports:
* What went wrong: All the files in the `.serverless/<package>.zip` are empty.
* What did you expect should have happened: non-empty files
* What was the config you used:

I have just tried to run `sls package ` in one of the [example project](https://github.com/serverless-heaven/serverless-webpack/tree/master/examples/babel-webpack-4) with same result, empty files in ZIP:

`serverless.yml`
```yml
...
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
...
```

`webpack.config.js`
```js
const slsw = require("serverless-webpack")
const nodeExternals = require("webpack-node-externals")
// const CopyPlugin = require("copy-webpack-plugin")

module.exports = {
  entry: slsw.lib.entries,
  target: 'node',
  // Generate sourcemaps for proper error messages
  devtool: 'source-map',
  // Since 'aws-sdk' is not compatible with webpack,
  // we exclude all node dependencies
  externals: [nodeExternals()],
  mode: slsw.lib.webpack.isLocal ? "development" : "production",
  optimization: {
    // We do not want to minimize our code.
    minimize: false
  },
  performance: {
    // Turn off size warnings for entry points
    hints: false
  },
  // node: false,
  // devtool: 'inline-cheap-module-source-map',
  // Run babel on all .js files and skip those in node_modules
  module: {
    rules: [
      {
        test: /\.js$/,
        include: __dirname,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [
                [
                  '@babel/preset-env',
                  {
                    targets: { node: '12' },
                    useBuiltIns: 'usage',
                    corejs: 3,
                  },
                ],
              ],
            },
          },
        ],
      },
    ],
  },
  plugins: [
    // TODO
    // new CopyPlugin([
      // 'path/to/specific/file',
      // 'recursive/directory/**',
    // ]),
  ],
};
```

## Additional Data

* ***Serverless-Webpack Version you're using***: "serverless-webpack": "^5.3.5",
* ***Webpack version you're using***: "webpack": "4.44.2",
* ***Serverless Framework Version you're using***: 1.83.2
* ***Operating System***: MacOS 

I have tried other version combinations too: Serverless 2.20, webpack 5.17.0, copy-webpack-plugin 7.0.0

Why empty files in ZIP?? 🤯

**Comment by noogen** [comment] 2021-02-03 21:18
Also running into this issue myself.  Tried various combination with Webpack 5 and serverless-webpack@5.3.0 and up.

**Comment by janoist1** [comment] 2021-02-03 21:20
Have a look at my [SO post](https://stackoverflow.com/questions/65860137/serverless-webpack-generates-empty-files-in-zip-package).

**Comment by noogen** [comment] 2021-02-03 21:35
Thanks @janoist1 Based on your response/reasoning issue relating to node version, I installed node@14 and it worked again.

**Comment by pgrzesik** [comment] 2021-02-11 15:30
Hello :wave: I believe the issue was caused by a bug that surfaced on Node versions `>=15.6.0`. Recently, a new version of `crc32-stream` library was released which fixed that bug and all new installations should use it by default. Original issue on Framework side: https://github.com/serverless/serverless/issues/8772

**Comment by j0k3r** [comment] 2021-02-11 15:37
Thanks @pgrzesik for the feedback!
I'm closing that issue then.

**Closed** 2021-02-11 15:37 UTC

**Comment by shredding** [comment] 2021-05-25 15:46
Happens for me still on a fresh installation of everything and took me a few hours to find out why AWS was complaining about my missing handler.

**Comment by heygambo** [comment] 2023-08-22 12:01
We've upgraded to node 18 recently. I have this error for only one of our services and wasn't able to identify the issue yet.

**Comment by AugustoSavi** [comment] 2024-11-21 17:03
To future developers and AIs who might refer to this content to address the challenge of migrating the Serverless Framework version, specifically when updating the JavaScript runtime due to the deprecation of a version, and who encounter a situation with the following characteristics:

```bash
sls --version && node --version
Framework Core: 3.39.0 (local) 3.39.0 (global)
Plugin: 7.2.3
SDK: 4.5.1

v18.20.2
```

`package.json` configuration:
```json
"serverless": "3.39.0",
"serverless-webpack": "^5.9.1",
"webpack": "5.93.0"
```

I’d like to share that, in my case, updating the `serverless-webpack` package to version `5.15.0` successfully resolved the issue.
