### ISSUE TITLE
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property

### ISSUE THREAD

**Issue by gordana16** [serverless-heaven/serverless-webpack#804] opened 2021-04-27 13:13 UTC
## Description

* What went wrong?
 I get the following deprecation warning when running serverless:
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessWebpack for "out"          
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
* What did you expect should have happened?
  no warning

## Additional Data

* ***Serverless-Webpack Version***: 5.4.1
* ***Serverless Framework Version you're using***: 2.35.0

**Comment by j0k3r** [comment] 2021-04-27 17:37
Duplicate of #764
Will be fixed in 5.4.2

**Closed by j0k3r** 2021-04-27 17:37 UTC
