### ISSUE TITLE
CLI options definitions were upgraded with "type" property

### ISSUE THREAD

**Issue by dobeerman** [serverless-heaven/serverless-webpack#765] opened 2021-04-06 17:03 UTC
# This is a Bug Report

## Description

For bug reports:
* Recently, in Serverless Framework CLI options definitions were upgraded. So, currently, I'm getting the following warning:

```text
Serverless: Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - ServerlessWebpack for "out"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA
```

## Additional Data

Framework Core: 2.33.1 (local)
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.8.1

**Comment by j0k3r** [comment] 2021-04-06 17:16
Duplicate of #764

**Closed by j0k3r** 2021-04-06 17:16 UTC
